let dummyButtons: String[] = ["C",
    "Java",
    "Python",
    "C++",
    "C#",
    "Visual Basic",
    "JavaScript",
    "PHP",
    "R",
    "SQL",
    "Swift",
    "Go",
    "Ruby",
    "Assembly language",
    "MATLAB",
    "Perl",
    "PL/SQL",
    "Scratch",
    "Classic Visual Basic",
    "Rust",
    "Objective-C",
    "Delphi/Object Pascal",
    "D",
    "Lisp",
    "Dart",
    "SAS",
    "Transact-SQL",
    "Logo",
    "COBOL",
    "Kotlin",
    "Groovy",
    "Scala",
    "Julia",
    "ABAP",
    "PowerShell",
    "OpenEdge ABL",
    "Fortran",
    "Lua",
    "VBScript",
    "Ada",
    "FoxPro",
    "ML",
    "LabVIEW",
    "TypeScript",
    "Haskell",
    "Scheme",
    "Prolog",
    "ActionScript",
    "Bash",]


export {dummyButtons};